### ISSUE TITLE
Warning messages of missing locale in javascript console.

### ISSUE THREAD

**Issue by Umair-Munir** [snipcart/snipcart-localization#42]
I have changed language from `en` to `de`. I am following each step given [here](https://docs.snipcart.com/javascript-api-reference/localization). Every time on loading page I get warning messages in my console. 

<img width="797" alt="screen shot 2017-03-19 at 5 39 47 pm" src="https://cloud.githubusercontent.com/assets/8552862/24082772/4437e3b2-0ccb-11e7-89cf-ff3160cf71b0.png">
How can I remove these warnings/errors?

**Comment by couellet** [comment]
Actually it looks like some strings haven't been translated. We plan on adding a "debug" mode to Snipcart to disable/enable logs. However, in the meantime the missing strings have to be added to de.js file.

I'll flag it as a bug on our side and we'll try to add the missing keys with the help of Google Translate but a PR would be awesome :)

**Comment by Umair-Munir** [comment]
It would be great if you would add this feature. For now I am adding missing string and will create PR soon.

**Comment by couellet** [comment]
We just added a way to do it ;) 

```js
document.addEventListener('snipcart.ready', function() {
  Snipcart.DEBUG = false;
});
```

It will be documented soon, it's being deployed at the moment.

**Comment by Umair-Munir** [comment]
Great Work 👍 . Thanks :)
