### ISSUE TITLE
Umlauts are converted to html entities

### ISSUE THREAD

**Issue by tobias-kuendig** [snipcart/snipcart-localization#48]
How can this be prevented?

![image](https://cloud.githubusercontent.com/assets/8600029/24849846/e46c68c2-1dcd-11e7-84b6-1445fdf9a5ba.png)

![image](https://cloud.githubusercontent.com/assets/8600029/24850122/0ff3334e-1dcf-11e7-8bf8-9b9d42dce3a1.png)

**Comment by couellet** [comment]
Sorry for the late reply on this one. I haven't been able to reproduce the issue on my end:

![image](https://snag.gy/pj9WVi.jpg)

Can you send us the link of the website where you are having the issue?

**Comment by tobias-kuendig** [comment]
Thanks for getting back to me. The problem was caused on my end.

I manually updated the translation with `registerLocale` since [my PR](https://github.com/snipcart/snipcart-localization/pull/46) was pending. Then my templating engine added the html entities while rendering the JS code.
