### ISSUE TITLE
Stripe and Profile strings are missing from the fr.js

### ISSUE THREAD

**Issue by jasonlemay** [snipcart/snipcart-localization#69]
It looks like many strings are missing from the fr.js, fr-FR.js and fr-CA.js : 

![screen shot 2018-04-03 at 1 08 25 pm](https://user-images.githubusercontent.com/2584073/38264231-620faa1e-3740-11e8-9613-30a0d06680da.png)

**Comment by JeanSebTr** [comment]
Salut @jasonlemay 

On maintient la version anglaise des fichiers de localisation mais on laisse le soin des autres langues à la communauté. Si vous faite une PR, on l'intégrera rapidement!


Cheers!

**Comment by jasonlemay** [comment]
Parfait, si j'ai deux minutes ce sera fait. Y-a-t'il un flag pour faire passer le plugin en mode production et éviter le bruit dans la console?

**Comment by JeanSebTr** [comment]
`Snipcart.DEBUG = false;`

Ça va cacher les logs si fait avant le changement de langue, mais possible qu'il en reste au load de la page.
