### ISSUE TITLE
EN Locale seems to have an issue at the bottom

### ISSUE THREAD

**Issue by Rosefalk** [snipcart/snipcart-localization#74]
Around the bottom of the file there's some string weirdness turning object keys into strings

**Comment by Rosefalk** [comment]
`stripe_processing_error:
"An error occurred while processing the card.",
"profile_credit_card":
"Credit card",
"profile_current_credit_card":
"Your current credit card ends with {0} and expires on {1} / {2}.",
"profile_update_card":
"Click here to update it",
"profile_saved_successfully":
"Your profile has been saved successfully.",
"profile_loading":
"Getting your profile information...",
"profile_saving":
"Saving your profile...",
"profile_billing_address":
"Billing address",
"profile_shipping_address":
"Shipping address",
"profile_edit_linktitle":
"Click here to edit your profile.",
"feature_not_supported_subscriptions": 
"We're sorry but subscriptions are not available with your payment gateway. This item can't be added.",
"profile_title": 
"Profile",
profile_edit_link:
"{0}"
});`

**Comment by JeanSebTr** [comment]
Hi there,

Sorry for the late reply and thanks for spotting that.

That's actually a problem with consistency inside the file but it won't cause any issues at runtime. In JSON, keys **MUST** be between double-quotes and JS object allow both keys with or without quotes around them.

We'll be reviewing how we do translations with the next version of the cart. We'll make sure to have mechanisms in place then to ensure consistent code style!
